### ISSUE TITLE
Duplicate number index signature

### ISSUE THREAD

**Issue by claudiuconstantin** [ui-router/angular-hybrid#70]
When compiling with Webpack I'm getting the following errors:

```
ERROR in [at-loader] ./node_modules/@uirouter/angular-hybrid/node_modules/@types/angular/jqlite.d.ts:29:5
    TS2375: Duplicate number index signature.

ERROR in [at-loader] ./node_modules/@uirouter/angular-hybrid/node_modules/@types/angular/jqlite.d.ts:824:5
    TS2374: Duplicate string index signature.
```
Here's my `packages` file:

[packages.txt](https://github.com/ui-router/angular-hybrid/files/1651943/packages.txt)

**Comment by christopherthielen** [comment]
Try adding `"skipLibCheck": true` to your `tsconfig.json`

**Comment by christopherthielen** [comment]
@claudiuconstantin  please report back if skipLibCheck fixes this issue.  I've also moved `@types/*` to devDependencies, so hopefully that might address it too.

**Comment by walterspieler** [comment]
I had the same error when upgrading to version 4. Downgrading to v3.1.10 did the trick for me.

**Comment by walterspieler** [comment]
```"skipLibCheck": true``` worked for me.

**Comment by harmnot** [comment]
I have some error like that also but from rxjs/internal 

it something like this .  I got many error

```
ERROR in node_modules/rxjs/internal/Subscription.d.ts(16,3): error TS2374: Duplicate string index signature.
    node_modules/rxjs/internal/Subscription.d.ts(17,3): error TS2393: Duplicate function implementation.
    node_modules/rxjs/internal/Subscription.d.ts(17,44): error TS1183: An implementation cannot be declared in ambient contexts.
    node_modules/rxjs/internal/Subscription.d.ts(20,3): error TS2393: Duplicate function implementation.
    node_modules/rxjs/internal/Subscription.d.ts(20,44): error TS1183: An implementation cannot be declared in ambient contexts.
    node_modules/typescript/lib/lib.es5.d.ts(124,5): error TS2411: Property 'constructor' of type 'Function' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(127,5): error TS2411: Property 'toString' of type '() => string' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(130,5): error TS2411: Property 'toLocaleString' of type '() => string' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(133,5): error TS2411: Property 'valueOf' of type '() => Object' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(139,5): error TS2411: Property 'hasOwnProperty' of type '(v: string | number | symbol) => boolean' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(145,5): error TS2411: Property 'isPrototypeOf' of type '(v: Object) => boolean' is not assignable to string index type 'string'.
    node_modules/typescript/lib/lib.es5.d.ts(151,5): error TS2411: Property 'propertyIsEnumerable' of type '(v: string | number | symbol) => boolean' is not assignable to string index type 'string'.
```

**Comment by g4b0-88** [comment]
> `"skipLibCheck": true` worked for me.

As 13-08-2019 I had the following message:
ERROR in node_modules/@progress/kendo-angular-grid/dist/es2015/columns/column-base.d.ts(18,3): error TS2374: Duplicate string index signature.

By adding the quoted line to tsconfig.json the message disappeared.

**Comment by 951565664** [comment]
I have some error like that also but from rxjs/internal  @bugsnag/browser

"skipLibCheck": true dosen't work for me.

**Comment by bojjakaseenadhreddy** [comment]
> I have some error like that also but from rxjs/internal @bugsnag/browser
> 
> "skipLibCheck": true dosen't work for me.

Please reinstall the rxjs library. 

**npm install rxjs**

**Comment by blingerson** [comment]
Is there any workaround or fix for this that doesn't include skipLibCheck being set?
